/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AntiVirus;

/**
 *
 * @author Tshikani, Zues
 */
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


public class QuarantineManager extends javax.swing.JFrame {

    /**
     * Creates new form QuarantineManager
     */
    private DefaultTableModel tableModel;   // dynamic table for quarantined files
    private int totalScanned = 0;           // total scanned files
    private int totalThreats = 0;           // total threats
    private int deletedCount = 0;           // deleted threats
    private boolean autoSetting = true;
    //private FileReader reader;
    
    public QuarantineManager() {
        initComponents();
        ButUndo.setEnabled(false);
        initTable();
        
        TableQuarantine.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

          // Enable Undo only when a row is selected in the table
        TableQuarantine.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) {
                ButUndo.setEnabled(TableQuarantine.getSelectedRow() != -1);
            }
        });
    
    //zaids code
     loadExistingQuarantineFiles();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuarantineManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuarantineManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuarantineManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuarantineManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuarantineManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        try (BufferedReader read = new BufferedReader(new FileReader("settings" + File.separator + "autoSetting.txt"))){
            String textLine;
            
            while((textLine = read.readLine()) != null){
                //textLine = read.readLine();
                
                if (textLine.equals("M")){
                    autoSetting = false;
                }
                //extentions.add(textLine);
            }
            
            read.close();
        } catch (IOException e){
            System.out.println("Error Reading Setting set to default");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initTable() {
        tableModel = new DefaultTableModel(
            new String[]{"File Name", "Quarantine Path","Original Path", "Status"}, 0
        );
        TableQuarantine.setModel(tableModel);
        updateSummary();
        TableQuarantine.setModel(tableModel);
        updateSummary();
    }

    /**
     * Add a threat file to the quarantine table
     */
    public void addThreatFile(String fileName, String originalPath) {
        if (autoSetting){
            try {
                String quarantineFolder = System.getProperty("user.home") + File.separator + "Documents" + File.separator + "Quarantine";
                Files.createDirectories(Path.of(quarantineFolder));

                // Create a unique quarantined file name
                String safeFileName = fileName + "_" + System.currentTimeMillis() + ".quarantined";
                File quarantineFile = new File(quarantineFolder, safeFileName);

                // Move the file
                File originalFile = new File(originalPath);
                Files.move(originalFile.toPath(), quarantineFile.toPath(), StandardCopyOption.REPLACE_EXISTING);

                // Create metadata file
                File metaFile = new File(quarantineFolder, safeFileName + ".meta");
                try (FileWriter writer = new FileWriter(metaFile)) {
                    writer.write("originalPath=" + originalPath + "\n");
                    writer.write("date=" + java.time.LocalDateTime.now());
                }

                // Add to table
                tableModel.addRow(new Object[]{fileName, quarantineFile.getAbsolutePath(), originalPath, "Quarantined"});
                totalThreats++;
                updateSummary();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Failed to quarantine file: " + e.getMessage());
                e.printStackTrace();
            }
        } else {
            tableModel.addRow(new Object[]{fileName," ",originalPath, "Not Quarantined"});
            totalThreats++;
            updateSummary();
        }
    }

    /**
     * Update scan summary label
     */
    public void updateSummary() {
        LabelQuickSummary.setText(
            "Files Scanned: " + totalScanned +
            " | Threats Found: " + totalThreats +
            " | Deleted: " + deletedCount
        );

        if (totalThreats == 0 && totalScanned > 0) {
            LabelQuickSummary.setText("✅ Scan Complete: No threats found.");
        }
    }

    /**
     * Called from Scanner when file is scanned
     */
    public void incrementScannedCount() {
        totalScanned++;
        updateSummary();
    }
    
    private void loadExistingQuarantineFiles() {
        try {
            String quarantineFolder = System.getProperty("user.home") + File.separator + "Documents" + File.separator + "Quarantine";
            File folder = new File(quarantineFolder);
            if (!folder.exists()) return;

            File[] files = folder.listFiles((dir, name) -> name.endsWith(".quarantined"));
            if (files == null) return;

            for (File quarantinedFile : files) {
                String fileName = quarantinedFile.getName().replace(".quarantined", "");
                String originalPath = "Unknown";

                // Look for .meta file
                File metaFile = new File(quarantinedFile.getAbsolutePath() + ".meta");
                if (metaFile.exists()) {
                    try (BufferedReader reader = new BufferedReader(new FileReader(metaFile))) {
                        String line;
                        while ((line = reader.readLine()) != null) {
                            if (line.startsWith("originalPath=")) {
                                originalPath = line.substring("originalPath=".length());
                                break;
                            }
                        }
                    }
                }

                tableModel.addRow(new Object[]{fileName, quarantinedFile.getAbsolutePath(), originalPath, "Quarantined"});
            }

            updateSummary();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButSettings = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ButDelete = new javax.swing.JButton();
        ButUndo = new javax.swing.JButton();
        ButExit = new javax.swing.JButton();
        ButBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableQuarantine = new javax.swing.JTable();
        LabelQuickSummary = new javax.swing.JLabel();
        butDelAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 16, 68));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Blacklist ");

        ButSettings.setBackground(new java.awt.Color(0, 0, 51));
        ButSettings.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        ButSettings.setForeground(new java.awt.Color(255, 255, 255));
        ButSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s1.png"))); // NOI18N
        ButSettings.setText("Settings");
        ButSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButSettingsMouseClicked(evt);
            }
        });
        ButSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSettingsActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        ButDelete.setBackground(new java.awt.Color(0, 0, 51));
        ButDelete.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        ButDelete.setForeground(new java.awt.Color(255, 255, 255));
        ButDelete.setText("Delete");
        ButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButDeleteActionPerformed(evt);
            }
        });

        ButUndo.setBackground(new java.awt.Color(0, 0, 51));
        ButUndo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        ButUndo.setForeground(new java.awt.Color(255, 255, 255));
        ButUndo.setText("Restore");
        ButUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButUndoActionPerformed(evt);
            }
        });

        ButExit.setBackground(new java.awt.Color(0, 0, 51));
        ButExit.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        ButExit.setForeground(new java.awt.Color(255, 255, 255));
        ButExit.setText("Exit");
        ButExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExitActionPerformed(evt);
            }
        });

        ButBack.setBackground(new java.awt.Color(0, 0, 51));
        ButBack.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        ButBack.setForeground(new java.awt.Color(255, 255, 255));
        ButBack.setText("Back");
        ButBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButBackActionPerformed(evt);
            }
        });

        TableQuarantine.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        TableQuarantine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "File Name", "File Path", "Status"
            }
        ));
        jScrollPane2.setViewportView(TableQuarantine);

        LabelQuickSummary.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        LabelQuickSummary.setForeground(new java.awt.Color(204, 0, 0));
        LabelQuickSummary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        butDelAll.setBackground(new java.awt.Color(0, 0, 51));
        butDelAll.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        butDelAll.setForeground(new java.awt.Color(255, 255, 255));
        butDelAll.setText("Delete All");
        butDelAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butDelAllMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelQuickSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butDelAll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(ButDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ButUndo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LabelQuickSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(ButUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(butDelAll, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(ButBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(ButExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ButSettings)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(897, 897, 897))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButSettingsActionPerformed

    private void ButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButDeleteActionPerformed
        // TODO add your handling code here:
        int[] selectedRows = TableQuarantine.getSelectedRows();

        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Please select one or more quarantined files to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to permanently delete the selected quarantined files?\nThis action cannot be undone.",
            "Confirm Deletion",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        DefaultTableModel model = (DefaultTableModel) TableQuarantine.getModel();
        int deletedCount = 0;

        // Delete selected files
        for (int i = selectedRows.length - 1; i >= 0; i--) {  // iterate in reverse to avoid shifting
            int row = selectedRows[i];
            String quarantinePath = (String) model.getValueAt(row, 1);
            File quarantinedFile = new File(quarantinePath);
            
            if (quarantinedFile.exists()) {
                
                if (quarantinedFile.delete()) {
                    File metaF = new File(quarantinePath + ".meta");
                    //System.out.println(metaF.);
                    if (metaF.exists()){
                        metaF.delete();
                    }
                    deletedCount++;
                } else {
                    System.err.println("Failed to delete: " + quarantinedFile.getAbsolutePath());
                }
            }

            // Remove from the table
            model.removeRow(row);
        }

        JOptionPane.showMessageDialog(this, deletedCount + " quarantined file(s) permanently deleted.");

        updateSummary();

    }//GEN-LAST:event_ButDeleteActionPerformed

    private void ButExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_ButExitActionPerformed

    private void ButBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButBackActionPerformed
        back();
    }//GEN-LAST:event_ButBackActionPerformed

    private void ButUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButUndoActionPerformed
        int[] selectedRows = TableQuarantine.getSelectedRows();

        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Please select one or more quarantined files to restore.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) TableQuarantine.getModel();
        int restoredCount = 0;

        for (int row : selectedRows) {
            String fileName = (String) model.getValueAt(row, 0);
            String quarantinePath = (String) model.getValueAt(row, 1);
            String originalPath = (String) model.getValueAt(row, 2);

            File quarantinedFile = new File(quarantinePath);
            File restoreTo = new File(originalPath);

            try {
                // Ensure the parent folder exists before restoring
                File parentDir = restoreTo.getParentFile();
                if (parentDir != null && !parentDir.exists()) {
                    parentDir.mkdirs();
                }

                // Move the file back to its original location
                Files.move(quarantinedFile.toPath(), restoreTo.toPath(), StandardCopyOption.REPLACE_EXISTING);

                // Update the status column to "Restored"
                model.setValueAt("Restored", row, 3);
                
                File metaF = new File(quarantinePath + ".meta");
                    //System.out.println(metaF.);
                    if (metaF.exists()){
                        metaF.delete();
                    }
                    
                restoredCount++;

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Failed to restore " + fileName + ": " + e.getMessage());
            }
        }

        JOptionPane.showMessageDialog(this, restoredCount + " file(s) restored successfully.");

        // Optionally, remove restored rows (reverse order to avoid index shifting)
        for (int i = selectedRows.length - 1; i >= 0; i--) {
            model.removeRow(selectedRows[i]);
        }

        ButUndo.setEnabled(false);
        updateSummary();


    }//GEN-LAST:event_ButUndoActionPerformed

    private void ButSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButSettingsMouseClicked
        SettingsPage page = new SettingsPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButSettingsMouseClicked

    private void butDelAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butDelAllMouseClicked
        DefaultTableModel model = (DefaultTableModel) TableQuarantine.getModel();

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "There are no quarantined files to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to permanently delete all quarantined files?",
            "Confirm Deletion",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        int deletedCount = 0;

        for (int i = 0; i < model.getRowCount(); i++) {
            String quarantinePath = (String) model.getValueAt(i, 1); // column 1 is the quarantine path
            File quarantinedFile = new File(quarantinePath);

            if (quarantinedFile.exists()) {
                if (quarantinedFile.delete()) {
                    File metaF = new File(quarantinePath + ".meta");
                    
                    if (metaF.exists()){
                        metaF.delete();
                    }
                    
                    deletedCount++;
                } else {
                    System.err.println("Failed to delete: " + quarantinedFile.getAbsolutePath());
                }
            }
        }

        // Clear the table after deleting
        model.setRowCount(0);

        JOptionPane.showMessageDialog(this, deletedCount + " quarantined file(s) deleted successfully.");

        updateSummary();
    }//GEN-LAST:event_butDelAllMouseClicked
     
    
     void back(){
        MainPage mainPage = new MainPage();
        mainPage.setVisible(true);
        this.dispose();
     } 
     
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuarantineManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuarantineManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuarantineManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuarantineManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        //</editor-fold>
/*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuarantineManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(() -> {
            new QuarantineManager().setVisible(true);
        });
*/
 //   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButBack;
    private javax.swing.JButton ButDelete;
    private javax.swing.JButton ButExit;
    private javax.swing.JButton ButSettings;
    private javax.swing.JButton ButUndo;
    private javax.swing.JLabel LabelQuickSummary;
    private javax.swing.JTable TableQuarantine;
    private javax.swing.JButton butDelAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
