/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AntiVirus;
import java.io.*;
import java.util.LinkedList;
import javax.swing.JOptionPane;
/**
 *
 * @author mjacu
 */
public class SettingsPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SettingsPage.class.getName());

    FileWriter writer;
    
    /**
     * Creates new form SettingsPage
     */
    public SettingsPage() {
        initComponents();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        String currentDir = System.getProperty("user.dir");
        
        
        String dirPath = currentDir + File.separator + "settings";

        // Create a File object representing the directory
        File directory = new File(dirPath);

        // Attempt to create the directory
        boolean dirCreated = directory.mkdir();
        
        settingReader();
        extSettingReader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resetButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        optionScroll = new javax.swing.JScrollPane();
        optionPane = new javax.swing.JPanel();
        exeCB = new javax.swing.JCheckBox();
        dllCB = new javax.swing.JCheckBox();
        scrCheckBox = new javax.swing.JCheckBox();
        batCheckBox = new javax.swing.JCheckBox();
        vbsCheckBox = new javax.swing.JCheckBox();
        jsCheckBox = new javax.swing.JCheckBox();
        ps1CheckBox = new javax.swing.JCheckBox();
        shCheckBox = new javax.swing.JCheckBox();
        msiCheckBox = new javax.swing.JCheckBox();
        jarCheckBox = new javax.swing.JCheckBox();
        zipCheckBox = new javax.swing.JCheckBox();
        docmCheckBox = new javax.swing.JCheckBox();
        dotmCheckBox = new javax.swing.JCheckBox();
        xlsmCheckBox = new javax.swing.JCheckBox();
        xltmCheckBox = new javax.swing.JCheckBox();
        potmCheckBox = new javax.swing.JCheckBox();
        ppsmCheckBox = new javax.swing.JCheckBox();
        pptmCheckBox = new javax.swing.JCheckBox();
        imgCheckBox = new javax.swing.JCheckBox();
        isoCheckBox = new javax.swing.JCheckBox();
        titleText = new javax.swing.JLabel();
        extTitleText = new javax.swing.JLabel();
        autoQuarantineCB = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 16, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resetButton.setBackground(new java.awt.Color(0, 0, 51));
        resetButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset to Default");
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });
        jPanel1.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 161, 38));

        applyButton.setBackground(new java.awt.Color(0, 0, 51));
        applyButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        applyButton.setForeground(new java.awt.Color(255, 255, 255));
        applyButton.setText("Apply");
        applyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applyButtonMouseClicked(evt);
            }
        });
        jPanel1.add(applyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 161, 38));

        exitButton.setBackground(new java.awt.Color(0, 0, 51));
        exitButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 140, 39));

        optionScroll.setBackground(new java.awt.Color(0, 51, 51));
        optionScroll.setForeground(new java.awt.Color(0, 51, 51));

        optionPane.setBackground(new java.awt.Color(0, 51, 102));

        exeCB.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        exeCB.setSelected(true);
        exeCB.setText("EXE Files");

        dllCB.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        dllCB.setSelected(true);
        dllCB.setText("DLL Files");

        scrCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        scrCheckBox.setSelected(true);
        scrCheckBox.setText("SCR Files");

        batCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        batCheckBox.setSelected(true);
        batCheckBox.setText("BAT Files");

        vbsCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        vbsCheckBox.setSelected(true);
        vbsCheckBox.setText("VBS Files");

        jsCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jsCheckBox.setSelected(true);
        jsCheckBox.setText("JS Files");

        ps1CheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        ps1CheckBox.setSelected(true);
        ps1CheckBox.setText("PS1 Files");

        shCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        shCheckBox.setSelected(true);
        shCheckBox.setText("SH Files");

        msiCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        msiCheckBox.setSelected(true);
        msiCheckBox.setText("MSI Files");

        jarCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jarCheckBox.setSelected(true);
        jarCheckBox.setText("JAR Files");
        jarCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarCheckBoxActionPerformed(evt);
            }
        });

        zipCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        zipCheckBox.setSelected(true);
        zipCheckBox.setText("ZIP Files");

        docmCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        docmCheckBox.setSelected(true);
        docmCheckBox.setText("Word Macro Extention Files");

        dotmCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        dotmCheckBox.setSelected(true);
        dotmCheckBox.setText("Macro Enabled Word Template Files");

        xlsmCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        xlsmCheckBox.setSelected(true);
        xlsmCheckBox.setText("Macro Enabled Excel Files");

        xltmCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        xltmCheckBox.setSelected(true);
        xltmCheckBox.setText("Macro Enabled Excel Template Files");

        potmCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        potmCheckBox.setSelected(true);
        potmCheckBox.setText("Macro Enabled Powerpoint Temple Files");

        ppsmCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        ppsmCheckBox.setSelected(true);
        ppsmCheckBox.setText("Macro Enabled Powerpoint Show Files");
        ppsmCheckBox.setToolTipText("");

        pptmCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        pptmCheckBox.setSelected(true);
        pptmCheckBox.setText("Macro Enabled Powerpoint Presentation Temple Files");

        imgCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        imgCheckBox.setSelected(true);
        imgCheckBox.setText("IMG Files");

        isoCheckBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        isoCheckBox.setSelected(true);
        isoCheckBox.setText("ISO Files");

        javax.swing.GroupLayout optionPaneLayout = new javax.swing.GroupLayout(optionPane);
        optionPane.setLayout(optionPaneLayout);
        optionPaneLayout.setHorizontalGroup(
            optionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPaneLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(optionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dllCB, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vbsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ps1CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jarCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dotmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xlsmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(potmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppsmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pptmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xltmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isoCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        optionPaneLayout.setVerticalGroup(
            optionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(dllCB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(scrCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(batCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(vbsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(ps1CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(msiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(shCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jarCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(zipCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(docmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(dotmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(xlsmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(xltmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(potmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(ppsmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pptmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(imgCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(isoCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        optionScroll.setViewportView(optionPane);

        jPanel1.add(optionScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 360, 390));

        titleText.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        titleText.setForeground(new java.awt.Color(255, 255, 255));
        titleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleText.setText("Settings");
        jPanel1.add(titleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 320, 60));

        extTitleText.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        extTitleText.setForeground(new java.awt.Color(255, 255, 255));
        extTitleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extTitleText.setText("Extentions to flag as a threat");
        jPanel1.add(extTitleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 360, 40));

        autoQuarantineCB.setBackground(new java.awt.Color(0, 16, 68));
        autoQuarantineCB.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        autoQuarantineCB.setForeground(new java.awt.Color(255, 255, 255));
        autoQuarantineCB.setText("Auto Quarantine");
        autoQuarantineCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoQuarantineCBActionPerformed(evt);
            }
        });
        jPanel1.add(autoQuarantineCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 250, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
       System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void applyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyButtonMouseClicked
        //===== Saving of user preferences to text file =====
        //Program returns to main page
        StringBuilder output = new StringBuilder("");
        
        if (exeCB.isSelected()) {
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        
        if (dllCB.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if (scrCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if (batCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(vbsCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(jsCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(ps1CheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(msiCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(shCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(jarCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(zipCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(docmCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(dotmCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(xlsmCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(xltmCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(potmCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(ppsmCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(pptmCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(imgCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }
        
        if(isoCheckBox.isSelected()){
            output.append("T\n");
        } else {
            output.append("F\n");
        }

        try {
            writer = new FileWriter("settings" + File.separator + "Settings.txt");
            writer.write("" + output);
            writer.close();
        } catch (IOException ex) {
            System.out.println("Settings error");
        }
        
        try {
            FileWriter wt = new FileWriter("settings" + File.separator + "autoSetting.txt");
            
            if(autoQuarantineCB.isSelected()){
                wt.write("A");
                wt.close();
            } else {
                wt.write("M");
                wt.close();
            }
        } catch (IOException ex){
            System.out.println("auto settings error");
        }
        
        
        MainPage main = new MainPage();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_applyButtonMouseClicked

    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseClicked
        //===== All checkboxes are selected when reset button is pushed
        
        exeCB.setSelected(true);
        dllCB.setSelected(true);
        scrCheckBox.setSelected(true);
        batCheckBox.setSelected(true);
        vbsCheckBox.setSelected(true);
        jsCheckBox.setSelected(true);
        ps1CheckBox.setSelected(true);
        msiCheckBox.setSelected(true);
        shCheckBox.setSelected(true);
        jarCheckBox.setSelected(true);
        zipCheckBox.setSelected(true);
        docmCheckBox.setSelected(true);
        dotmCheckBox.setSelected(true);
        xlsmCheckBox.setSelected(true);
        xltmCheckBox.setSelected(true);
        potmCheckBox.setSelected(true);
        ppsmCheckBox.setSelected(true);
        pptmCheckBox.setSelected(true);
        autoQuarantineCB.setSelected(true);
        isoCheckBox.setSelected(true);
        imgCheckBox.setSelected(true);
    }//GEN-LAST:event_resetButtonMouseClicked

    private void autoQuarantineCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoQuarantineCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoQuarantineCBActionPerformed

    private void jarCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarCheckBoxActionPerformed

    }//GEN-LAST:event_jarCheckBoxActionPerformed

    //===== Reads in the data from the autoSetting text file =====
    //If file is empty, default setting is applied
    //If file doesn't exist, then the file will be created
    private void settingReader(){
        try (BufferedReader read = new BufferedReader(new FileReader("settings" + File.separator + "autoSetting.txt"))){
            String line = read.readLine();
            
            if(line != null){
                if (line.equals("A")){
                    autoQuarantineCB.setSelected(true);
                } else if (line.equals("M")){
                    autoQuarantineCB.setSelected(false);
                } else {
                    JOptionPane.showMessageDialog(null,"Auto Quarantine Preference File tampered with. Default Settings applied.");
                    autoQuarantineCB.setSelected(true);
                }
                 read.close();
            } else {
                JOptionPane.showMessageDialog(null,"Auto Quarantine Preference File empty. Default Settings applied.");
                autoQuarantineCB.setSelected(true);
                read.close();
            }
        } catch (IOException e){
            
            JOptionPane.showMessageDialog(null,"Auto Quarantine Preference File doesn't exist. Default Settings applied and file has been created.");
            autoQuarantineCB.setSelected(true);
                
            try {
                FileWriter wt = new FileWriter("settings" + File.separator + "autoSetting.txt");
                wt.close();
            } catch (IOException ex){
                System.out.println("auto settings error");
            }
        }
    }
    
    // ===== Reading the suspicious extension preferences set by the user =====
    // Reads in the T or F character to be reflected on the screen
    // If file has been tamped with, default settings are enabled, regardless of data in file
    private void extSettingReader(){
        LinkedList<String> exten = new LinkedList<String>();
        String line;
        boolean flag = false;
        try (BufferedReader read = new BufferedReader(new FileReader("settings" + File.separator + "Settings.txt"))){
            line = read.readLine();
            int count = 0;
            while(line != null && count < 20){
                exten.add(line);
                if (!exten.get(count).equals("T") && !exten.get(count).equals("F")){
                    flag = true;
                }
                
                count++;
                line = read.readLine();
            }
            
            if (count <20) {
                flag = true;
                JOptionPane.showMessageDialog(null, "Tampering in Extention Settings detected. Default Settings applied");
            }
        } catch (IOException e){
            JOptionPane.showMessageDialog(null, "Extension Preference File doesn't exist. Default Settings applied and file has been created.");
            try {
                FileWriter wt = new FileWriter("settings" + File.separator + "Settings.txt");
                flag = true;
                wt.close();
            } catch (IOException ex){
                System.out.println("Extension settings error");
            }
        }
        
        if (!flag) {
            if (exten.get(0).equals("T")) {
                exeCB.setSelected(true);
            } else {
                exeCB.setSelected(false);
            }


            if (exten.get(1).equals("T")){
                dllCB.setSelected(true);
            } else {
                dllCB.setSelected(false);
            }

            if (exten.get(2).equals("T")){
                scrCheckBox.setSelected(true);
            } else {
                scrCheckBox.setSelected(false);
            }

            if (exten.get(3).equals("T")){
                batCheckBox.setSelected(true);
            } else {
                batCheckBox.setSelected(false);
            }

            if(exten.get(4).equals("T")){
                vbsCheckBox.setSelected(true);
            } else {
                vbsCheckBox.setSelected(false);
            }

            if(exten.get(5).equals("T")){
                jsCheckBox.setSelected(true);
            } else {
                jsCheckBox.setSelected(false);
            }

            if(exten.get(6).equals("T")){
                ps1CheckBox.setSelected(true);
            } else {
                ps1CheckBox.setSelected(false);
            }

            if(exten.get(7).equals("T")){
                msiCheckBox.setSelected(true);
            } else {
                msiCheckBox.setSelected(false);
            }

            if(exten.get(8).equals("T")){
                shCheckBox.setSelected(true);
            } else {
                shCheckBox.setSelected(false);
            }

            if(exten.get(9).equals("T")){
                jarCheckBox.setSelected(true);
            } else {
                jarCheckBox.setSelected(false);
            }

            if(exten.get(10).equals("T")){
                zipCheckBox.setSelected(true);
            } else {
                zipCheckBox.setSelected(false);
            }

            if(exten.get(11).equals("T")){
                docmCheckBox.setSelected(true);
            } else {
                docmCheckBox.setSelected(false);
            }

            if(exten.get(12).equals("T")){
                dotmCheckBox.setSelected(true);
            } else {
                dotmCheckBox.setSelected(false);
            }

            if(exten.get(13).equals("T")){
                xlsmCheckBox.setSelected(true);
            } else {
                xlsmCheckBox.setSelected(false);
            }

            if(exten.get(14).equals("T")){
                xltmCheckBox.setSelected(true);
            } else {
                xltmCheckBox.setSelected(false);
            }

            if(exten.get(15).equals("T")){
                potmCheckBox.setSelected(true);
            } else {
                potmCheckBox.setSelected(false);
            }

            if(exten.get(16).equals("T")){
                ppsmCheckBox.setSelected(true);
            } else {
                ppsmCheckBox.setSelected(false);
            }

            if(exten.get(17).equals("T")){
                pptmCheckBox.setSelected(true);
            } else {
                pptmCheckBox.setSelected(false);
            }

            if(exten.get(18).equals("T")){
                imgCheckBox.setSelected(true);
            } else {
                imgCheckBox.setSelected(false);
            }

            if(exten.get(19).equals("T")){
                isoCheckBox.setSelected(true);
            } else {
                isoCheckBox.setSelected(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tampering in Extention Settings detected. Default Settings applied");
            exeCB.setSelected(true);
            dllCB.setSelected(true);
            scrCheckBox.setSelected(true);
            batCheckBox.setSelected(true);
            vbsCheckBox.setSelected(true);
            jsCheckBox.setSelected(true);
            ps1CheckBox.setSelected(true);
            msiCheckBox.setSelected(true);
            shCheckBox.setSelected(true);
            jarCheckBox.setSelected(true);
            zipCheckBox.setSelected(true);
            docmCheckBox.setSelected(true);
            dotmCheckBox.setSelected(true);
            xlsmCheckBox.setSelected(true);
            xltmCheckBox.setSelected(true);
            potmCheckBox.setSelected(true);
            ppsmCheckBox.setSelected(true);
            pptmCheckBox.setSelected(true);
            autoQuarantineCB.setSelected(true);
            isoCheckBox.setSelected(true);
            imgCheckBox.setSelected(true);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(() -> new SettingsPage().setVisible(true));
  //  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JCheckBox autoQuarantineCB;
    private javax.swing.JCheckBox batCheckBox;
    private javax.swing.JCheckBox dllCB;
    private javax.swing.JCheckBox docmCheckBox;
    private javax.swing.JCheckBox dotmCheckBox;
    private javax.swing.JCheckBox exeCB;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel extTitleText;
    private javax.swing.JCheckBox imgCheckBox;
    private javax.swing.JCheckBox isoCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jarCheckBox;
    private javax.swing.JCheckBox jsCheckBox;
    private javax.swing.JCheckBox msiCheckBox;
    private javax.swing.JPanel optionPane;
    private javax.swing.JScrollPane optionScroll;
    private javax.swing.JCheckBox potmCheckBox;
    private javax.swing.JCheckBox ppsmCheckBox;
    private javax.swing.JCheckBox pptmCheckBox;
    private javax.swing.JCheckBox ps1CheckBox;
    private javax.swing.JButton resetButton;
    private javax.swing.JCheckBox scrCheckBox;
    private javax.swing.JCheckBox shCheckBox;
    private javax.swing.JLabel titleText;
    private javax.swing.JCheckBox vbsCheckBox;
    private javax.swing.JCheckBox xlsmCheckBox;
    private javax.swing.JCheckBox xltmCheckBox;
    private javax.swing.JCheckBox zipCheckBox;
    // End of variables declaration//GEN-END:variables
}
